# Generated by Django 3.2.6 on 2021-08-23 09:14

from django.db import migrations, models
import django.db.models.deletion
import tummyapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tummy_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.CharField(max_length=100)),
                ('ordered', models.BooleanField()),
                ('delivered', models.CharField(choices=[('pending', 'PENDING'), ('delivered', 'DELIVERED'), ('return', 'RETURN')], max_length=50)),
                ('remarks', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('package', models.CharField(choices=[('employee_package', 'EMPLOYEE PACKAGE'), ('total_veg_package', 'TOTAL VEG PACKAGE')], max_length=50)),
                ('week', models.CharField(choices=[('first_week', 'FIRST WEEK'), ('second_week', 'SECOND WEEK'), ('third_week', 'THIRD WEEK'), ('fourth_week', 'FOURTH WEEK')], max_length=50)),
                ('day', models.CharField(choices=[('sunday', 'SUNDAY'), ('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tummy_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent', models.CharField(choices=[('dairy', 'DAIRY'), ('beverages', 'BEVERAGES'), ('hard drinks', 'HARD DRINKS'), ('soft drinks', 'SOFT DRINKS'), ('groceries', 'GROCERIES'), ('kitchen item', 'KITCHEN ITEM'), ('madi in nepal', 'MADE IN NEPAL'), ('restaurants', 'RESTAURANTS')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_package_price_historys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('package_product', models.CharField(choices=[('first_week', 'FIRST WEEK'), ('second_week', 'SECOND WEEK'), ('third_week', 'THIRD WEEK'), ('fourth_week', 'FOURTH WEEK')], max_length=50)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('dairy', 'DAIRY'), ('beverages', 'BEVERAGES'), ('hard drinks', 'HARD DRINKS'), ('soft drinks', 'SOFT DRINKS'), ('groceries', 'GROCERIES'), ('kitchen item', 'KITCHEN ITEM'), ('madi in nepal', 'MADE IN NEPAL'), ('restaurants', 'RESTAURANTS')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tummy_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tummy_images/')),
                ('is_active', models.CharField(choices=[('unknown', 'UNKNOWN'), ('yes', 'YES'), ('no', 'NO')], default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_logistic', models.BooleanField(default=False)),
                ('staff_status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('superuser_status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('password_confirmation', models.CharField(max_length=100)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='User_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('lunch_time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Product_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ordered', models.BooleanField()),
                ('checkout', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_price_historys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.CharField(max_length=100)),
                ('ordered', models.BooleanField()),
                ('delivered', models.CharField(choices=[('pending', 'PENDING'), ('delivered', 'DELIVERED'), ('return', 'RETURN')], max_length=50)),
                ('remarks', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package_product_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('package', models.CharField(choices=[('employee_package', 'EMPLOYEE PACKAGE'), ('total_veg_package', 'TOTAL VEG PACKAGE')], max_length=50)),
                ('week', models.CharField(choices=[('first_week', 'FIRST WEEK'), ('second_week', 'SECOND WEEK'), ('third_week', 'THIRD WEEK'), ('fourth_week', 'FOURTH WEEK')], max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.package_orders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email_otps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(default=tummyapp.models.random_string, max_length=6)),
                ('validated', models.BooleanField(default=True)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now=True)),
                ('forgot', models.BooleanField()),
                ('forgot_logged', models.BooleanField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tummyapp.customers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
